config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_sign_in', to: 'users/sessions#new_admin'
  end
  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  resources :genres, :except => [:show]
  resources :shops do
    resource :favorites, only: [:create, :destroy]
    resource :saved_shops, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get '*path', to: 'application#render_404'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shop_genres
  has_many :shops, through: :shop_genres
  validates :name, length: { maximum: 255 }
  validates :name, presence: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ edit update destroy ]
  before_action :only_admin

  def index
    @genres = Genre.all.page(params[:page])
  end

  def new
    @genre = Genre.new
  end

  def edit
  end

  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genres_path, notice: "ジャンルが作成されました。" }
        format.json { render :index, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_path, notice: "ジャンルが更新されました。" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "ジャンルが削除されました。" }
      format.json { head :no_content }
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true, html: {class: "container has-background-white column is-10 mt-4 box box-radius"}) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "") %>件のエラーが検出されました。:</h2>

      <ul>
        <% genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field columns is-vcentered m-0">
    <%= form.label :name, class: "label column is-2 mb-0" %>
    <%= form.text_field :name, class: "input column is-10 is-fullwidth", :placeholder => "カフェ" %>
  </div>

  <div class="actions">
    <%  if @genre.persisted? %>
      <%= form.submit t("attributes.update"), class: "button is-rounded is-fullwidth is-link" %>
    <% else %>
      <%= form.submit t("attributes.create"), class: "button is-rounded is-fullwidth is-link" %>
    <% end %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">ジャンル編集画面</h1>
    </div>
  </div>
</section>


<%= render 'form', genre: @genre %>

<div class="has-text-centered container column is-8">
  <%= link_to t("attributes.back"), genres_path, class: "button is-link is-rounded is-fullwidth is-light" %>
</div>

app/views/genres/index.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">ジャンル一覧</h1>
    </div>
  </div>
</section>

<div class="container has-background-white column is-10 mt-4 box box-radius">
  <%= link_to '新しいジャンルを作成する', new_genre_path, class: "button is-link is-rounded is-fullwidth mb-2" %>
  <table class="table is-fullwidth is-bordered">
    <% @genres.each do |genre| %>
      <tbody>
        <tr class="has-text-centered">
          <td class="is-size-5"><%= genre.name  %></td>
          <td class="is-size-5"><%= link_to "編集", edit_genre_path(genre), class: "button is-rounded is-link" %></td>
          <td class="is-size-5"><%= link_to "削除", genre, data: { confirm: "本当に削除してもよろしいですか？" }, class: "button is-rounded is-danger", method: :delete %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>
<div class="has-text-centered container column is-8">
  <%= link_to '戻る', root_path, class: "button is-link is-rounded is-fullwidth is-light" %>
</div>
<%= paginate @genres %>

app/views/genres/new.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">ジャンル作成画面</h1>
    </div>
  </div>
</section>

<%= render 'form', genre: @genre %>

<div class="has-text-centered container column is-8">
  <%= link_to t("attributes.back"), genres_path, class: "button is-link is-rounded is-fullwidth is-light" %>
</div>

app/views/genres/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>