config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_sign_in', to: 'users/sessions#new_admin'
  end
  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  resources :genres, :except => [:show]
  resources :shops do
    resource :favorites, only: [:create, :destroy]
    resource :saved_shops, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get '*path', to: 'application#render_404'
end

app/models/shop.rb
class Shop < ApplicationRecord
  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }
  has_many :favorites, dependent: :destroy
  has_many :saved_shops, dependent: :destroy
  has_many :browsing_histories, dependent: :destroy
  has_many :shop_genres, dependent: :destroy
  has_many :genres, through: :shop_genres
  validates :name, length: { maximum: 255 }
  validates :prefecture, length: { maximum: 10 }
  validates :city, length: { maximum: 255 }
  validates :address, length: { maximum: 255 }
  with_options presence: true do
    validates :name
    validates :prefecture
    validates :city
    validates :address
    validates :latitude
    validates :longitude
    validates :business_hour
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]
  before_action :only_admin, except: %i[ index show ]

  def index
    @genres = Genre.all
    @q = Shop.includes(:genres, :favorites, :saved_shops).ransack(params[:q])
    @shops = @q.result(distinct: true).order(:id).page(params[:page])
  end

  def show
    if current_user
      add_browsing_histories
      delete_browsing_histories
    end
  end

  def new
    @shop = Shop.new
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: "ショップが登録されました。" }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "ショップ情報が更新されました。" }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "ショップ情報が削除されました。" }
      format.json { head :no_content }
    end
  end

  private
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(
      :name, :prefecture, :city,
      :address, :latitude, :longitude,
      :business_hour, :cashless, :bike_rack,
      :remarks, { genre_ids: []})
  end

  def add_browsing_histories
    if BrowsingHistory.where(user_id: current_user.id, shop_id: @shop.id) == []
      @browsing_history = BrowsingHistory.new
      @browsing_history.user_id = current_user.id
      @browsing_history.shop_id = @shop.id
      @browsing_history.save!
    end
  end

  def delete_browsing_histories
    if current_user.browsing_histories.count > 4
      current_user.browsing_histories.first.destroy!
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_favorite.html.erb
<% if Favorite.find_by(user_id: current_user.id, shop_id: shop.id) %>
  <%= link_to shop_favorites_path(shop_id: shop.id), method: :delete, remote: true, class: "favorite-link delete-#{shop.id}" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
    </svg>
  <% end %>
<% else %>
  <%= link_to shop_favorites_path(shop_id: shop.id), method: :post, remote: true, class: "favorite-link post-#{shop.id}" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
      <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
    </svg>
  <% end %>
<% end %>
<%= shop.favorites.length %>

app/views/shops/_form.html.erb
<h2 class="is-underlined has-text-white has-text-weight-bold has-text-centered is-size-3">ショップ情報</h2>
<%= form_with(model: shop, local: true, html: {class: "container has-background-white column is-10 mt-4 box box-radius"}) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "") %>件のエラーが検出されました。:</h2>

      <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field columns is-vcentered m-0">
    <%= form.label :name, class: "label column is-2 mb-0" %>
    <%= form.text_field :name, class: "input column is-10 is-fullwidth", :placeholder => "ロードバイクカフェ" %>
  </div>

  <div class="field columns is-vcentered m-0 my-1 select">
    <%= form.label :prefecture, class: "label column is-2 mb-0" %>
    <%= form.select :prefecture, Shop.prefectures.keys.to_a, {}, class: "column is-10 is-fullwidth" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :city, class: "label column is-2 mb-0" %>
    <%= form.text_field :city, class: "input column is-10", :placeholder => "渋谷区" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :address, class: "label column is-2 mb-0" %>
    <%= form.text_field :address, class: "input column is-10", :placeholder => "松濤1-1-1" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :latitude, class: "label column is-2 mb-0" %>
    <%= form.text_field :latitude, class: "input column is-10", :placeholder =>"30.000000" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :longitude, class: "label column is-2 mb-0" %>
    <%= form.text_field :longitude, class: "input column is-10", :placeholder => "135.000000" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :business_hour, class: "label column is-2 mb-0" %>
    <%= form.text_area :business_hour, class: "input column is-10", :placeholder => "年中無休" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :cashless, class: "label column checkbox is-2" %>
    <%= form.check_box :cashless, class: "column is-10" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :bike_rack, class: "label column checkbox is-2" %>
    <%= form.check_box :bike_rack, class: "column is-10" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= form.label :remarks, class: "label column is-2 mb-0" %>
    <%= form.text_area :remarks, class: "input column is-10", :placeholder => "ロードバイク乗りが集うカフェです。" %>
  </div>

  <div class="filed columns is-vcentered m-0">
    <%= form.label :genre, class: "label column is-2 mb-0" %>
    <%= form.collection_check_boxes(:genre_ids, Genre.all, :id, :name, class: "checkbox is-10") %>
  </div>
  <br />
  <div class="actions">
    <%  if @shop.persisted? %>
      <%= form.submit t("attributes.update"), class: "button is-rounded is-fullwidth is-link" %>
    <% else %>
      <%= form.submit t("attributes.create"), class: "button is-rounded is-fullwidth is-link" %>
    <% end %>
  </div>
<% end %>

app/views/shops/_saved_shop.html.erb
<% if SavedShop.find_by(user_id: current_user.id, shop_id: shop.id) %>
  <%= link_to shop_saved_shops_path(shop_id: shop.id), method: :delete, remote: true, class: "saved-shop-link delete-#{shop.id}" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-fill" viewBox="0 0 16 16">
      <path d="M2 2v13.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2z"/>
    </svg>
  <% end %>
<% else %>
  <%= link_to shop_saved_shops_path(shop_id: shop.id), method: :post, remote: true, class: "saved-shop-link post-#{shop.id}" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
      <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
    </svg>
  <% end %>
<% end %>
<%= shop.saved_shops.length %>

app/views/shops/edit.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">ショップ情報編集</h1>
    </div>
  </div>
</section>

<%= render 'form', shop: @shop %>

<div class="has-text-centered container column is-8">
  <%= link_to '戻る', shops_path, class: "button is-link is-rounded is-fullwidth is-light" %>
</div>

app/views/shops/index.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">Cycle Depot</h1>
      <p class="subtitle">This is a Database for cyclist friendly shops.<br></p>
    </div>
  </div>
</section>

<div class="columns is-vcentered mt-0">
  <%= image_tag "smartphone.png", class: "is-6 column image " %>
  <p class="is-6 column has-text-white has-text-weight-bold has-text-centered">
  ロードバイクで行きやすいお店を簡単に検索することができるサービスです。<br>
  ちょっと休憩をしたい。この辺でロードバイクで行けるお店ないかな？<br><br>
  そんな時のお店探しなら<br>
  <span class="is-size-2">Cycle Depot!!</span>
  </p>
</div>

<h2 class="is-underlined has-text-white has-text-weight-bold has-text-centered is-size-3">ショップ検索</h2>
<%= search_form_for @q, html: {class: "container has-background-white column is-10 mt-4 box box-radius"} do |f| %>
  <div class="columns mx-3 my-1 is-vcentered">
    <%= f.label :name, "店名", class: "label column is-2 mb-0 " %>
    <%= f.search_field :name_cont, class: "input column is-10" %>
  </div>
  <div class="columns mx-3 my-1 is-vcentered select">
    <%= f.label :prefecture, "都道府県", class: "label column is-2 mb-0" %>
    <%= f.select :prefecture_eq_any, Shop.prefectures.to_a, { include_blank: "指定なし" }, class: "column is-10 is-fullwidth" %>
  </div>
  <div class="columns mx-3 my-1 is-vcentered select">
    <%= f.label :genres_name, "ジャンル", class: "label column is-2 mb-0" %>
    <%= f.collection_select :genres_id_eq, @genres, :id, :name, { include_blank: "指定なし" }, class: "column is-10 is-fullwidth" %><br />
  </div>
  <div class="columns mx-3 my-1 is-vcentered checkbox">
    <%= f.label :cashless, "キャッシュレス", class: "label column is-2 mb-0" %>
    <%= f.check_box :cashless_true, {class:"checkbox"}, checked_value = "true", unchecked_value= "" %>
  </div>
  <div class="columns mx-3 my-1 is-vcentered checkbox">
    <%= f.label :bile_rack, "サイクルラック", class: "label column is-2 mb-0 py-0" %>
    <%= f.check_box :bike_rack_true, {class:"checkbox"}, ckecked_value = "true", unchecked_value = "" %>
  </div>
  <br />
  <%= f.submit "検索", class: "button is-rounded is-fullwidth is-link" %>
<% end %>

<h2 class="is-underlined has-text-white has-text-weight-bold has-text-centered is-size-3">ショップリスト</h2>
<section class="container">
  <div class="columns is-multiline is-centered">
    <% @shops.each do |shop| %>
      <div class="column is-5" >
        <div class="card is-shady">
          <div class="card-content pb-1">
            <div class="clickable" onclick="location.href='<%= shop_path(shop.id) %>'" style=":hover cursor: pointer;">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4"><%= shop.name %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 512 512"><path d="M0 256C0 397.4 114.6 512 256 512s256-114.6 256-256S397.4 0 256 0S0 114.6 0 256zM241 377c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l87-87-87-87c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0L345 239c9.4 9.4 9.4 24.6 0 33.9L241 377z"/></svg>
                  </p>
                  <p class="subtitle is-6"><%= shop.prefecture %><%= shop.city %>
                    <% shop.genres.each do |genre| %>
                      <%= genre.name %>
                    <% end %>
                  </p>
                </div>
              </div>
              <div class="content">
                サイクルラック: <%= shop.bike_rack == true ? "有" : "無" %>
              </div>
            </div>
            <footer class="card-footer is-vcentered">
              <% if current_user %>
                <div id="favorite-<%= shop.id %>" class="card-footer-item py-1">
                  <%= render partial: "favorite", remote: true, locals: { shop: shop } %>
                </div>
                <div id="saved-shop-<%= shop.id %>" class="card-footer-item py-1">
                  <%= render partial: "saved_shop", remote: true, locals: { shop: shop } %>
                </div>
              <% end %>
            </footer>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @shops %>
  <% if @shops == [] %>
    <p class="has-text-white has-text-centered has-text-bold mb-3">※お探しの条件に当てはまるショップはありませんでした。</p>
  <% end %>
</section>

app/views/shops/new.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">ショップ情報登録</h1>
    </div>
  </div>
</section>

<%= render 'form', shop: @shop %>

<div class="has-text-centered container column is-8">
  <%= link_to '戻る', shops_path, class: "button is-link is-rounded is-fullwidth is-light" %>
</div>

app/views/shops/show.html.erb
<input type="hidden" id="latitude" value="<%= @shop.latitude %>">
<input type="hidden" id="longitude" value="<%= @shop.longitude %>">

<div class="container has-background-white column is-10 mt-4 box box-radius">
  <p class="has-text-centered">
    <span class="has-text-weight-bold is-size-3"><%= @shop.name %></span><br />
    <% @shop.genres.each do |genre| %>
      <%= genre.name %>
    <% end %>
  </p>
  <% if current_user %>
    <div class="columns is-centered has-text-centered my-0">
      <div id="favorite-<%= @shop.id %>" class="column p-0 is-3 is-size-5">
        <%= render partial: "./shops/favorite", remote: true, locals: { shop: @shop } %>
      </div>
      <div id="saved-shop-<%= @shop.id %>" class="column p-0 is-3 is-size-5">
        <%= render partial: "./shops/saved_shop", remote: true, locals: { shop: @shop } %>
      </div>
    </div>
  <% end %>

  <h2 class="is-size-4 mb-2 has-text-centered is-underlined">店舗情報</h2>
  <table class="table is-fullwidth is-bordered">
    <tbody>
      <tr class="has-text-centered">
        <td class="is-size-5">住所</td>
        <td class="is-size-5"><%= "#{@shop.prefecture}#{@shop.city}#{@shop.address}" %></td>
      </tr>
      <tr class="has-text-centered">
        <td class="is-size-5">営業時間</td>
        <td class="is-size-5"><%= @shop.business_hour %></td>
      </tr>
      <tr class="has-text-centered">
        <td class="is-size-5">キャッシュレス</td>
        <td class="is-size-5"><%= @shop.cashless == true ? "対応" : "非対応" %></td>
      </tr>
      <tr class="has-text-centered">
        <td class="is-size-5">サイクルラック</td>
        <td class="is-size-5"><%= @shop.bike_rack == true ? "有" : "無" %></td>
      </tr>
      <tr class="has-text-centered">
        <td class="is-size-5">備考</td>
        <td class="is-size-5"><%= @shop.remarks %></td>
      </tr>
      <tr class="has-text-centered">
        <td class="is-size-5">地図</td>
        <td class="is-size-5"><div id="map"></div></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="has-text-centered container column is-8">
  <% if current_user && current_user.admin? %>
    <%= link_to '編集', edit_shop_path(@shop), class: "button is-rounded is-link is-fullwidth" %><br />
    <%= link_to '削除', @shop, data: { confirm: "本当に削除してもよろしいですか？" }, class: "button is-rounded is-link is-fullwidth", method: :delete %><br />
  <% end %>
  <%= link_to '戻る', shops_path, class: "button is-rounded is-link is-light is-fullwidth" %>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>