config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_sign_in', to: 'users/sessions#new_admin'
  end
  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  resources :genres, :except => [:show]
  resources :shops do
    resource :favorites, only: [:create, :destroy]
    resource :saved_shops, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get '*path', to: 'application#render_404'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :saved_shops, dependent: :destroy
  has_many :shops, through: :saved_shops
  has_many :browsing_histories, dependent: :destroy
  validates :name, length: { maximum: 255 }
  validates :email, length: { maximum: 255 }
  validates :password, length: { in: 6..255 }
  validates :admin, inclusion: [true, false]
  with_options presence: true do
    validates :name
    validates :email
  end

  def self.guest
    find_or_create_by!(email: "guest@gmail.com") do |user|
      user.name = "ゲストユーザー"
      user.email = "guest@gmail.com"
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.admin = false
    end
  end

  def self.admin
    find_or_create_by!(email: "admin@gmail.com") do |user|
      user.name = "アドミンユーザー"
      user.email = "admin@gmail.com"
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.admin = true
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end

  def new_admin
    user = User.admin
    sign_in user
    redirect_to root_path, notice: "アドミンユーザーとしてログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :only_admin, only: %i[ index ]
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :only_your_own, only: %i[ show ]

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @saved_shops = @user.shops.page(params[:page])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "ユーザー情報が更新されました。"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notive: "アカウントを削除しました。" }
      format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def only_your_own
    redirect_to root_path unless User.find(params[:id]) == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, html: { class: "container has-background-white column is-10 mt-4 box box-radius" }) do |f| %>


  <div class="field columns is-vcentered m-0">
    <%= f.label :name, class: "label column is-2 mb-0" %>
    <%= f.text_field :name, class: "input column is-10 is-fullwidth", autofocus: true, autocomplete: "name", :placeholder => "田中太郎" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= f.label :email, class: "label column is-2 mb-0" %>
    <%= f.email_field :email, class: "input column is-10 is-fullwidth", autofocus: true, autocomplete: "email", :placeholder => "taro@email.com" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= f.label :password, class: "label column is-2 mb-0" %>
    <%= f.password_field :password, class: "input column is-10 is-fullwidth", autocomplete: "new-password", :placeholder => "tanaka" %>
  </div>

  <div class="field columns is-vcentered m-0">
    <%= f.label :password_confirmation, class: "label column is-2 mb-0" %>
    <%= f.password_field :password_confirmation, class: "input column is-10 is-fullwidth", autocomplete: "new-password", :placeholder => "tanaka" %>
  </div>

  <% if current_user.admin? %>
    <div class="field columns is-vcentered m-0">
      <%= f.label :admin, class: "label column checkbox is-2 mb-0" %>
      <%= f.check_box :admin, class: "column is-10" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t("attributes.update"), class: "button is-rounded is-fullwidth is-link" %>
  </div>
<% end %>

<div class="has-text-centered container column is-8">
  <%= link_to '戻る', users_path, class: "button is-link is-rounded is-fullwidth is-light" %>
</div>

app/views/users/index.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">ユーザー一覧</h1>
    </div>
  </div>
</section>

<div class="container has-background-white column is-10 mt-4 box box-radius">
  <table class="table is-fullwidth is-bordered">
    <% User.all.each do |user| %>
      <tbody>
        <tr class="has-text-centered">
          <td class="is-size-5"><%= user.name  %></td>
          <td class="is-size-5"><%= link_to "編集", edit_user_path(user), class: "button is-rounded is-link" %></td>
          <td class="is-size-5"><%= link_to "削除", user, data: { confirm: "#{user.name}を削除してもよろしいですか？" }, class: "button is-rounded is-danger", method: :delete %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>
<div class="has-text-centered container column is-8">
  <%= link_to '戻る', root_path, class: "button is-link is-rounded is-fullwidth is-light" %>
</div>
<%= paginate @users %>

app/views/users/show.html.erb
<section class="hero is-small has-background-white">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="has-text-weight-bold title">マイページ</h1>
    </div>
  </div>
</section>

<h2 class="is-underlined has-text-white has-text-weight-bold has-text-centered is-size-3">登録情報</h2>
<div class="container has-background-white column is-10 mt-4 box box-radius">
  <p class="columns has-text-centered">
    <span class="column is-2"><strong>ユーザーネーム</strong></span>
    <span class="column is-10"><%= @user.name %></span>
  </p>
  <p class="columns has-text-centered">
    <span class="column is-2"><strong>メールアドレス</strong></span>
    <span class="column is-10"><%= @user.email %></span>
  </p>
  <%= link_to "編集",  edit_user_registration_path, class: "button is-rounded is-fullwidth is-link" %>
</div>

<h2 class="is-underlined has-text-white has-text-weight-bold has-text-centered is-size-3 mb-3">保存したショップ</h2>
<section class="container">
  <div class="columns is-multiline is-centered">
    <% @saved_shops.each do |shop| %>
      <% shop = Shop.find(shop.id) %>
      <div class="column is-5" >
        <div class="card is-shady">
          <div class="card-content pb-1">
            <div class="clickable" onclick="location.href='<%= shop_path(shop.id) %>'" style=":hover cursor: pointer;">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4"><%= shop.name %></p>
                  <p class="subtitle is-6"><%= shop.prefecture %><%= shop.city %>
                    <% shop.genres.each do |genre| %>
                      <%= genre.name %>
                    <% end %>
                  </p>
                </div>
              </div>

              <div class="content">
                サイクルラック: <%= shop.bike_rack == true ? "有" : "無" %>
              </div>
            </div>
            <footer class="card-footer is-vcentered">
              <% if current_user %>
                <div id="favorite-<%= shop.id %>" class="card-footer-item py-1">
                  <%= render partial: "shops/favorite", remote: true, locals: { shop: shop } %>
                </div>
                <div id="saved-shop-<%= shop.id %>" class="card-footer-item py-1">
                  <%= render partial: "shops/saved_shop", remote: true, locals: { shop: shop } %>
                </div>
              <% end %>
            </footer>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @saved_shops %>
  </div>
</section>

<h2 class="is-underlined has-text-white has-text-weight-bold has-text-centered is-size-3 mb-3">最近閲覧したショップ</h2>
<section class="container">
  <div class="columns is-multiline is-centered">
    <% @user.browsing_histories.each do |browsing_history| %>
      <% shop = Shop.find(browsing_history.shop_id) %>
      <div class="column is-5" >
        <div class="card is-shady">
          <div class="card-content pb-1">
            <div class="clickable" onclick="location.href='<%= shop_path(shop.id) %>'" style=":hover cursor: pointer;">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4"><%= shop.name %></p>
                  <p class="subtitle is-6"><%= shop.prefecture %><%= shop.city %>
                    <% shop.genres.each do |genre| %>
                      <%= genre.name %>
                    <% end %>
                  </p>
                </div>
              </div>

              <div class="content">
                サイクルラック: <%= shop.bike_rack == true ? "有" : "無" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>