config/routes.rb
Rails.application.routes.draw do
  root 'shops#index'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    post 'users/admin_sign_in', to: 'users/sessions#new_admin'
  end
  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  resources :genres, :except => [:show]
  resources :shops do
    resource :favorites, only: [:create, :destroy]
    resource :saved_shops, only: [:create, :destroy]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  get '*path', to: 'application#render_404'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cycle Depot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('logo.png') %>
  </head>

  <body class="container has-navbar-fixed-top">
    <nav class="navbar is-fixed-top">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to image_tag("logo.png", class:"navbar-item image p-0 logo"), shops_path %>
          <span class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div class="navbar-menu" id="navMenu">
          <div class="navbar-end">
            <% if user_signed_in? && current_user.admin == false %>
              <%= link_to "マイページ", user_path(current_user.id), class: "navbar-item has-text-centered" %>
              <%= link_to "ログアウト", destroy_user_session_path, class: "navbar-item has-text-centered", method: :delete %>
            <% elsif user_signed_in? == false %>
              <%= link_to "ログイン", new_user_session_path, class: "navbar-item has-text-centered" %>
              <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "navbar-item has-text-centered" %>
              <%= link_to 'アドミンログイン（閲覧用）', users_admin_sign_in_path, method: :post, class: "navbar-item has-text-centered" %>
              <%= link_to "ユーザー登録", new_user_registration_path, class: "navbar-item has-text-centered" %>
            <% else %>
              <%= link_to "マイページ", user_path(current_user.id), class: "navbar-item has-text-centered" %>
              <%= link_to "ユーザー一覧", users_path, class: "navbar-item has-text-centered" %>
              <%= link_to "ジャンル一覧", genres_path, class: "navbar-item has-text-centered" %>
              <%= link_to "ショップ登録", new_shop_path, class: "navbar-item has-text-centered" %>
              <%= link_to "ログアウト", destroy_user_session_path, class: "navbar-item has-text-centered", method: :delete %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <p class="notice has-background-white"><%= notice %></p>
    <p class="alert has-background-white"><%= alert %></p>
    <%= yield %>
  </body>
</html>